language: node_js
node_js:
  - '10'

branches:
  only:
  - master
notifications:
  email: false

install:
  - npm install
script:
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $PAGES_TOKEN
  keep_history: true
  local_dir: public/
