language: node_js
node_js:
  - '10'

branches:
  only:
  - master
notifications:
  email: false

install:
  - npm install
script:
  - npm run build
deploy:
  provider: pages:git
  local_dir: public/

env:
  - PATH_PREFIX=/forestry-blog

